# Generated by Django 3.2.7 on 2021-10-07 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211006_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thred',
            new_name='Thread',
        ),
        migrations.AddField(
            model_name='announce',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Comment', 'コメント'), ('Follow', 'フォロー'), ('Like', 'いいね'), ('Announce', 'お知らせ')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notified_item_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notified_item_type',
            field=models.CharField(choices=[('Idea', 'アイデア'), ('Memo', 'メモ'), ('Comment', 'コメント'), ('FollowedUser', 'フォローされたユーザー'), ('Announce', 'お知らせ')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='is_following',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
