# Generated by Django 3.2.7 on 2021-10-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_google_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_comment', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_idea', to='api.idea'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_memo', to='api.memo'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='target_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_idea', to='api.idea'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='target_memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_memo', to='api.memo'),
        ),
    ]
