# Generated by Django 3.2.7 on 2021-10-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211010_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
