# Generated by Django 3.2.7 on 2021-10-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_idea_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='display_name',
            field=models.CharField(max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
